name: TwerkingGarden
version: ${project.version}
author: NCBPFluffyBear (Original by TheBusyBiscuit)
description: A Slimefun Addon that adds new Plants and dishes to the game
api-version: '1.13'

main: me.fluffybear.twerkinggarden.TwerkingGarden

depend: [Slimefun]